"""add city_code to delivery_points

Revision ID: 1e02bc3eb256
Revises: 0003bd3a9428
Create Date: 2025-09-25 11:40:59.846618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e02bc3eb256'
down_revision: Union[str, Sequence[str], None] = '0003bd3a9428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_points', sa.Column('city_code', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'delivery_points', 'cities', ['city_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_points', type_='foreignkey')
    op.drop_column('delivery_points', 'city_code')
    # ### end Alembic commands ###
