"""add relationship with tariff and delivery_mode

Revision ID: 4b2491601a82
Revises: ece3a80227ee
Create Date: 2025-10-02 19:55:17.337299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b2491601a82'
down_revision: Union[str, Sequence[str], None] = 'ece3a80227ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('tariffs', sa.Column('weight_min', sa.Float(), nullable=True))
    op.add_column('tariffs', sa.Column('weight_max', sa.Float(), nullable=True))
    op.add_column('tariffs', sa.Column('weight_calc_max', sa.Float(), nullable=True))
    op.add_column('tariffs', sa.Column('length_min', sa.Integer(), nullable=True))
    op.add_column('tariffs', sa.Column('length_max', sa.Integer(), nullable=True))
    op.add_column('tariffs', sa.Column('width_min', sa.Integer(), nullable=True))
    op.add_column('tariffs', sa.Column('width_max', sa.Integer(), nullable=True))
    op.add_column('tariffs', sa.Column('height_min', sa.Integer(), nullable=True))
    op.add_column('tariffs', sa.Column('height_max', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tariffs_ibfk_2'), 'tariffs', type_='foreignkey')
    op.drop_constraint(op.f('tariffs_ibfk_1'), 'tariffs', type_='foreignkey')
    op.drop_column('tariffs', 'period_min')
    op.drop_column('tariffs', 'from_city_code')
    op.drop_column('tariffs', 'delivery_mode')
    op.drop_column('tariffs', 'delivery_date_range')
    op.drop_column('tariffs', 'tariff_code')
    op.drop_column('tariffs', 'period_max')
    op.drop_column('tariffs', 'to_city_code')
    op.drop_column('tariffs', 'delivery_sum')
    op.drop_column('tariffs', 'calendar_min')
    op.drop_column('tariffs', 'calendar_max')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('calendar_max', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tariffs', sa.Column('calendar_min', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tariffs', sa.Column('delivery_sum', mysql.FLOAT(), nullable=True))
    op.add_column('tariffs', sa.Column('to_city_code', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True))
    op.add_column('tariffs', sa.Column('period_max', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tariffs', sa.Column('tariff_code', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False))
    op.add_column('tariffs', sa.Column('delivery_date_range', mysql.JSON(), nullable=True))
    op.add_column('tariffs', sa.Column('delivery_mode', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tariffs', sa.Column('from_city_code', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True))
    op.add_column('tariffs', sa.Column('period_min', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tariffs_ibfk_1'), 'tariffs', 'cities', ['from_city_code'], ['code'])
    op.create_foreign_key(op.f('tariffs_ibfk_2'), 'tariffs', 'cities', ['to_city_code'], ['code'])
    op.drop_column('tariffs', 'height_max')
    op.drop_column('tariffs', 'height_min')
    op.drop_column('tariffs', 'width_max')
    op.drop_column('tariffs', 'width_min')
    op.drop_column('tariffs', 'length_max')
    op.drop_column('tariffs', 'length_min')
    op.drop_column('tariffs', 'weight_calc_max')
    op.drop_column('tariffs', 'weight_max')
    op.drop_column('tariffs', 'weight_min')
    op.drop_column('tariffs', 'id')
    # ### end Alembic commands ###
