"""add relationship with tariff and delivery_mode

Revision ID: 688ff5d9e684
Revises: 4b2491601a82
Create Date: 2025-10-02 19:59:44.761548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688ff5d9e684'
down_revision: Union[str, Sequence[str], None] = '4b2491601a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tariff_name', sa.String(length=255), nullable=True),
    sa.Column('tariff_description', sa.String(length=255), nullable=True),
    sa.Column('weight_min', sa.Float(), nullable=True),
    sa.Column('weight_max', sa.Float(), nullable=True),
    sa.Column('weight_calc_max', sa.Float(), nullable=True),
    sa.Column('length_min', sa.Integer(), nullable=True),
    sa.Column('length_max', sa.Integer(), nullable=True),
    sa.Column('width_min', sa.Integer(), nullable=True),
    sa.Column('width_max', sa.Integer(), nullable=True),
    sa.Column('height_min', sa.Integer(), nullable=True),
    sa.Column('height_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'delivery_modes', 'tariffs', ['tariff_id'], ['id'])
    op.drop_index(op.f('postal_codes_cities_FK'), table_name='postal_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('postal_codes_cities_FK'), 'postal_codes', ['city_code'], unique=False)
    op.drop_constraint(None, 'delivery_modes', type_='foreignkey')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
