"""add name to delivery_points

Revision ID: 7a35539ee4c5
Revises: e4b55d082829
Create Date: 2025-10-01 23:33:43.074435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a35539ee4c5'
down_revision: Union[str, Sequence[str], None] = 'e4b55d082829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_points', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('delivery_points_ibfk_1'), 'delivery_points', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_points', 'cities', ['city_code'], ['code'])
    op.drop_constraint(op.f('postal_codes_cities_FK'), 'postal_codes', type_='foreignkey')
    op.create_foreign_key(None, 'postal_codes', 'cities', ['city_code'], ['code'])
    op.drop_constraint(op.f('tariffs_ibfk_1'), 'tariffs', type_='foreignkey')
    op.drop_constraint(op.f('tariffs_ibfk_2'), 'tariffs', type_='foreignkey')
    op.create_foreign_key(None, 'tariffs', 'cities', ['from_city_code'], ['code'])
    op.create_foreign_key(None, 'tariffs', 'cities', ['to_city_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tariffs', type_='foreignkey')
    op.drop_constraint(None, 'tariffs', type_='foreignkey')
    op.create_foreign_key(op.f('tariffs_ibfk_2'), 'tariffs', 'cities', ['to_city_code'], ['code'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('tariffs_ibfk_1'), 'tariffs', 'cities', ['from_city_code'], ['code'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'postal_codes', type_='foreignkey')
    op.create_foreign_key(op.f('postal_codes_cities_FK'), 'postal_codes', 'cities', ['city_code'], ['code'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'delivery_points', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_points_ibfk_1'), 'delivery_points', 'cities', ['city_code'], ['code'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('delivery_points', 'name')
    # ### end Alembic commands ###
