"""deliverypointmodel added

Revision ID: c98e5a562cd3
Revises: 
Create Date: 2025-09-22 19:27:50.098269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c98e5a562cd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_points',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('address_comment', sa.String(length=255), nullable=True),
    sa.Column('nearest_station', sa.String(length=255), nullable=True),
    sa.Column('nearest_metro_station', sa.String(length=255), nullable=True),
    sa.Column('work_time', sa.String(length=255), nullable=True),
    sa.Column('phones', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('PVZ', 'POSTAMAT'), nullable=True),
    sa.Column('owner_code', sa.String(length=255), nullable=True),
    sa.Column('take_only', sa.Boolean(), nullable=True),
    sa.Column('is_handout', sa.Boolean(), nullable=True),
    sa.Column('is_reception', sa.Boolean(), nullable=True),
    sa.Column('is_dressing_room', sa.Boolean(), nullable=True),
    sa.Column('is_marketplace', sa.Boolean(), nullable=True),
    sa.Column('is_ltl', sa.Boolean(), nullable=True),
    sa.Column('have_cashless', sa.Boolean(), nullable=True),
    sa.Column('have_cash', sa.Boolean(), nullable=True),
    sa.Column('have_fast_payment_system', sa.Boolean(), nullable=True),
    sa.Column('allowed_cod', sa.Boolean(), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('office_image_list', sa.JSON(), nullable=True),
    sa.Column('work_time_list', sa.JSON(), nullable=True),
    sa.Column('work_time_exception_list', sa.JSON(), nullable=True),
    sa.Column('weight_min', sa.Float(), nullable=True),
    sa.Column('weight_max', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('distance', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('filfillment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('regions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('region_code', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('country_code', mysql.ENUM('RU', 'EN', 'TJ'), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fias_region_guid', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('kladr_region_code', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('region_code'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('delivery_points')
    # ### end Alembic commands ###
