"""add tariffs table

Revision ID: e4b55d082829
Revises: 1e02bc3eb256
Create Date: 2025-09-25 13:34:18.370330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4b55d082829'
down_revision: Union[str, Sequence[str], None] = '1e02bc3eb256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('tariff_code', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('tariff_name', sa.String(length=255), nullable=True),
    sa.Column('tariff_description', sa.String(length=255), nullable=True),
    sa.Column('delivery_mode', sa.Integer(), nullable=True),
    sa.Column('delivery_sum', sa.Float(), nullable=True),
    sa.Column('period_min', sa.Integer(), nullable=True),
    sa.Column('period_max', sa.Integer(), nullable=True),
    sa.Column('calendar_min', sa.Integer(), nullable=True),
    sa.Column('calendar_max', sa.Integer(), nullable=True),
    sa.Column('delivery_date_range', sa.JSON(), nullable=True),
    sa.Column('from_city_code', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('to_city_code', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['from_city_code'], ['cities.code'], ),
    sa.ForeignKeyConstraint(['to_city_code'], ['cities.code'], ),
    sa.PrimaryKeyConstraint('tariff_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariffs')
    # ### end Alembic commands ###
