"""add delivery mode table

Revision ID: ece3a80227ee
Revises: 7a35539ee4c5
Create Date: 2025-10-02 16:09:42.931774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ece3a80227ee'
down_revision: Union[str, Sequence[str], None] = '7a35539ee4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_modes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_mode', sa.String(length=255), nullable=True),
    sa.Column('delivery_mode_name', sa.String(length=255), nullable=True),
    sa.Column('tariff_code', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tariff_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_modes')
    # ### end Alembic commands ###
